language: php

php:
  - 5.6

before_script:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get update
  - sudo apt-get install erlang erlang-nox
  - sudo apt-get install rabbitmq-server
  - composer install

script:
  - php example/async_consumer.php