language: php

php:
  - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install nginx
  - sudo cp -R /home/travis/build/Panace9i/test/example /usr/share/nginx/html
  - cd /usr/share/nginx/html
  - ls -l

script:
  - curl -vvv localhost