language: php

php:
  - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install nginx php5-cgi php5-fpm
  - sudo mv travis-build/nginx.default.config /etc/nginx/sites-enabled/default
  - sudo service nginx restart

script:
  - curl -vvv localhost/examples/inline.php
