language: php

php:
  - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install nginx php5.6-cgi php5.6-fpm
  - sudo cp -R /home/travis/build/Panace9i/test/examples /usr/share/nginx/html

script:
  - curl -vvv localhost/examples/inline.php
